version: '3.8'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.6
    restart: unless-stopped
    env_file:
     - .env
    ports:
      - 3306:3306
    volumes:
      - ./data/:/var/lib/mysql
